### ISSUE TITLE
Custom Dragon drops

### ISSUE THREAD

**Issue by Pixle36** [hraponssi/Dragon-dmg#2]
could there be a way to add custom items with nbt data and color codes, or if there is could there be an example of how to do this in the description of the plugin

**Comment by hraponssi** [comment]
In version 1.4.2 I've added %world% and %coordinates% placeholders to the killrewards section, so you can spawn custom items at the dragons death location via commands. (Doing it this way is far easier than spawning the items with nbt via the plugin itself)

The default config now includes an example execute command that will spawn an elytra at the dragon's death location: 
"execute in minecraft:%world% run summon item %coordinates% {Item:{id:"minecraft:elytra",Count:1}}"

**Comment by Pixle36** [comment]
While it is a good work around, it allows the reward to go to anyone instead of only the killer of the dragon like how it works already

**Comment by hraponssi** [comment]
Based on the original issue my understanding was you were looking for a feature that allows for "custom dragon drops", so items dropped by the dragon. If it is to be killer only how would it differ from the existing solutions with running a give command for %killer% in the kill rewards section?
